# Generated by Django 2.1.4 on 2019-01-04 19:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('town', models.CharField(max_length=120, verbose_name='Town')),
                ('street', models.CharField(max_length=120, verbose_name='Street')),
                ('house_number', models.PositiveSmallIntegerField(verbose_name='House number')),
                ('apartment_number', models.PositiveSmallIntegerField(verbose_name='Apartment number')),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(max_length=254, unique=True, verbose_name='Email address')),
                ('email_type', models.PositiveSmallIntegerField(choices=[(1, 'Cellphone'), (2, 'Home')], verbose_name='Email type')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Group name')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120, verbose_name='First name')),
                ('surname', models.CharField(max_length=120, verbose_name='Surname')),
                ('description', models.TextField(verbose_name='Description')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contacts_book.Address', verbose_name='Address')),
                ('groups', models.ManyToManyField(blank=True, to='contacts_book.Group', verbose_name='Groups')),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'People',
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number format: '+## ### ### ###'", regex='^\\+?\\d{2}? ?(\\d{3}?(-| )?){3}$')], verbose_name='Phone number')),
                ('phone_type', models.PositiveSmallIntegerField(choices=[(1, 'Cellphone'), (2, 'Home'), (3, 'Work')], verbose_name='Phone type')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts_book.Person', verbose_name='Person')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(blank=True, to='contacts_book.Person', verbose_name='Members'),
        ),
        migrations.AddField(
            model_name='email',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts_book.Person'),
        ),
    ]
