# Generated by Django 2.1.4 on 2019-01-04 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts_book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='avatar',
            field=models.ImageField(default=1, upload_to='avatars'),
            preserve_default=False,
        ),
    ]
