# Generated by Django 2.1.4 on 2019-01-07 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts_book', '0002_auto_20190105_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='apartment_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Apartment number'),
        ),
        migrations.AlterField(
            model_name='person',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contacts_book.Address', verbose_name='Address'),
        ),
    ]
