# Generated by Django 2.1.4 on 2019-01-11 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts_book', '0003_auto_20190107_1937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='groups',
        ),
    ]
