# Generated by Django 2.1.4 on 2019-01-11 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts_book', '0004_remove_person_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='groups',
            field=models.ManyToManyField(blank=True, to='contacts_book.Group', verbose_name='Groups'),
        ),
    ]
